Qa local
hmrc/advance-valuation-rulings-acceptance pull request #10
Opened 2023-01-26 15:05 UTC by sitaramireddytanuboddi

2023-01-27 11:27 UTC, SathyaHmrc approved these changes

2023-01-27 11:35 UTC, Froom2 requested changes

2023-01-27 11:35 UTC, Froom2 commented on src/test/scala/uk/gov/hmrc/test/ui/pages/ThisServiceIsDesignedForThose.scala
> +        .findElement(By.xpath(ele_link_AdvanceTariffRulings))
Why did we switch to using xpath to select this? Generally IDs are less fragile as I understand it

2023-01-27 11:35 UTC, Froom2 commented on src/test/scala/uk/gov/hmrc/test/ui/pages/UploadSupportingDocuments.scala
> +  val ele_UpliadDocument  = "//input[@id='file-upload-1']"
Is this meant to say UploadDocument?

2023-01-27 11:35 UTC, Froom2 commented on src/test/scala/uk/gov/hmrc/test/ui/pages/MethodSelectionPage.scala
> +      case _ => driver.findElement(By.id(ele_Method1)).click()
This might be more readable if you put method 1 at the top, and have method 6 as the catch-all at the end

2023-01-27 11:35 UTC, Froom2 commented on src/test/scala/uk/gov/hmrc/test/ui/pages/HaveYouFoundTheCommodityCode.scala
> +    println("Name of the goods is -  " + GoodsName)
Can remove this :)

2023-01-27 11:35 UTC, Froom2 commented on src/test/resources/features/GoodsInformation.feature
Why does this page have a separate feature file?

2023-01-27 13:32 UTC, sitaramireddytanuboddi commented on src/test/scala/uk/gov/hmrc/test/ui/pages/ThisServiceIsDesignedForThose.scala
> +        .findElement(By.xpath(ele_link_AdvanceTariffRulings))
Updated to id property

2023-01-27 13:32 UTC, sitaramireddytanuboddi commented on src/test/scala/uk/gov/hmrc/test/ui/pages/UploadSupportingDocuments.scala
> +  val ele_UpliadDocument  = "//input[@id='file-upload-1']"
updated the variable name

2023-01-27 13:33 UTC, sitaramireddytanuboddi commented on src/test/scala/uk/gov/hmrc/test/ui/pages/MethodSelectionPage.scala
> +      case _ => driver.findElement(By.id(ele_Method1)).click()
updated as per the comment

2023-01-27 13:33 UTC, sitaramireddytanuboddi commented on src/test/scala/uk/gov/hmrc/test/ui/pages/HaveYouFoundTheCommodityCode.scala
> +    println("Name of the goods is -  " + GoodsName)
Removed

2023-01-27 13:34 UTC, sitaramireddytanuboddi commented on src/test/resources/features/GoodsInformation.feature
removed the feature file

2023-01-27 17:19 UTC, sitaramireddytanuboddi commented on src/test/scala/uk/gov/hmrc/test/ui/pages/WhichCountryAreTheGoodsComingFrom.scala
> +    Thread.sleep(1000)
Since country's list is loading dynamically(After entering the country name in the text box)i kept 1 sec wait statement.

2023-01-30 12:14 UTC, Froom2 requested changes

2023-01-30 13:11 UTC, sitaramireddytanuboddi commented on src/test/scala/uk/gov/hmrc/test/ui/pages/UploadSupportingDocuments.scala
> +      .findElement(By.xpath(ele_UploadDocument))
Updated to id

2023-01-30 13:46 UTC, Froom2 approved these changes

2023-01-30 13:59 UTC, merged